In [19]:
#import pandas and decide the files to check
import pandas as pd
df = pd.read_csv('raw_customer_shopping_behavior.csv')

In [20]:
#check the first few rows of the dataframe
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [21]:
#check how dataset looks like like datatype, columns, and null values
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [22]:
#check the summary statistics of the dataset
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [23]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [24]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [25]:
#create reference list for the median values of 'Review Rating' based on 'Category' - remove NA value from the calculation
category_median = df.groupby('Category')['Review Rating'].transform('median')
df['Review Rating'] = df['Review Rating'].fillna(category_median)

In [26]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [27]:
#replace header to snake case to better aligned with operating system
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
#replace to purchase amount usd to purchase_amount
df.columns = df.columns.str.replace('_(usd)','')
#or we can do df.columns = df.columns.str.lower().str.replace(' ','_')
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [28]:
# Create age_group column using qcut (4 equal-sized groups)
labels = ['Young Adult', 'Adult', 'Middle-Aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

# Create age_group_2 column using cut (Fixed 'bin=' to 'bins=')
df['age_group_2'] = pd.cut(df['age'], bins=[0, 25, 50, 100])

# Create age_group_3 column using cut (Fixed 'bin=' to 'bins=' and labels)
labels_3 = ['Young', 'Middle', 'Senior']
df['age_group_3'] = pd.cut(df['age'], bins=[0, 25, 50, 100], labels = labels_3)

# View all columns together side-by-side
df[['age', 'age_group', 'age_group_2', 'age_group_3']].head(10)

   age    age_group age_group_2 age_group_3
0   55  Middle-Aged   (50, 100]      Senior
1   19  Young Adult     (0, 25]       Young
2   50  Middle-Aged    (25, 50]      Middle
3   21  Young Adult     (0, 25]       Young
4   45  Middle-Aged    (25, 50]      Middle
5   46  Middle-Aged    (25, 50]      Middle
6   63       Senior   (50, 100]      Senior
7   27  Young Adult    (25, 50]      Middle
8   26  Young Adult    (25, 50]      Middle
9   57  Middle-Aged   (50, 100]      Senior

In [29]:
#check the unique value and how many per each
df['frequency_of_purchases'].unique()
df['frequency_of_purchases'].value_counts()

# Define mapping dictionary (matching exact casing) 
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly':7,
    'Every 3 Months': 90,
    'Annually':365,
    'Quarterly' : 90,
    'Monthly': 30,
    'Bi-Weekly': 14
}
# Create new column purchase_frequency days
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [30]:
df[['frequency_of_purchases', 'purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [31]:
df['frequency_of_purchases'].unique()

<StringArray>
[   'Fortnightly',         'Weekly',       'Annually',      'Quarterly',
      'Bi-Weekly',        'Monthly', 'Every 3 Months']
Length: 7, dtype: str

In [32]:
df[['discount_applied','promo_code_used']].head()

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes

In [33]:
#Check if discount_applied and promo_code_used is duplicated, if yes, we don't need both of them
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [34]:
#Remove promo_code_used as both of them are duplicated. By default, Pandas operates on rows (axis=0) so axis=1: Looks at Column Names.
df = df.drop('promo_code_used', axis=1)
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'age_group_2', 'age_group_3',
       'purchase_frequency_days'],
      dtype='str')

### Option A: Save to CSV (Manual Import via MySQL Workbench)
> **Use case:** Quick manual review or when sharing raw flat files.
#Save cleaned dataframe to the project folder, add index = false so it don' create extra column with 0,1,2 as stt

df.to_csv('cleaned_customer_shopping_behavior.csv', index=False)

### Option B: Direct Automated Push to MySQL (Recommended)
> **Use case:** Automated ETL pipeline. Streams data straight into MySQL without creating intermediate files.

In [ ]:
%pip install sqlalchemy pymysql
from sqlalchemy import create_engine
import pandas as pd

# 1. Setup my MySQL credentials
user = "root"  # or my MySQL username
password = "-----" #hidden
host = "localhost"
port = "3306"  # default MySQL port
database = "customer_behavior"  # database you created in Workbench

# 2. Create the MySQL connection engine
engine = create_engine(
    f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"
)

# 3. Automatically push your clean DataFrame straight into MySQL
df.to_sql(
    name="customers",
    con=engine,
    if_exists="replace",
    index=False,
)

print("Data pushed to MySQL successfully!")

Requirement already satisfied: sqlalchemy in c:\Users\huong\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (2.0.51)
Requirement already satisfied: pymysql in c:\Users\huong\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)
Requirement already satisfied: greenlet>=1 in c:\Users\huong\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from sqlalchemy) (3.5.4)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\huong\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.
Data pushed to MySQL successfully!